# NumPy Practical  01
1D and 2D metrics

#### Import Library

In [1]:
# Import Library
import numpy as np

#### Create 1D array

In [5]:
# create a 1d array
arry_1d = np.array([1, 2, 3, 4, 5])
print(arry_1d)

[1 2 3 4 5]


In [6]:
# check the type of array
type(arry_1d)

numpy.ndarray

In [9]:
# check the dimensional
arry_1d.ndim

1

In [10]:
# check the size of array
arry_1d.size

5

In [11]:
# check the shape 
arry_1d.shape      # (row, col)

(5,)

In [12]:
# check the data type
arry_1d.dtype

dtype('int32')

#### Creat 2D array

In [14]:
# create a 2D array
arry_2d = np.array([[1, 2, 3 , 4, 5], [1, 2, 3, 4 , 5]])
print(arry_2d)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [20]:
# check the dim
arry_2d.ndim

2

In [16]:
# check the type of array
type(arry_2d)

numpy.ndarray

In [17]:
# check the size of array
arry_2d.size

10

In [18]:
# check the shape of array
arry_2d.shape                   # (row = 2, col = 5)

(2, 5)

In [19]:
# check the data type
arry_2d.dtype

dtype('int32')