# NumPy Practical  03
NumPy Function

#### Import Library

In [2]:
import numpy as np

#### arange()

In [3]:
arr_1d = np.arange(0, 11)           # (start, end, step)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
Even_1D_Array = np.arange(0, 11, 2)
print(Even_1D_Array)

[ 0  2  4  6  8 10]


#### linspace()

In [5]:
arr = np.linspace(1, 10, 4)    # create 4 value between 1 to 10
print(arr)

[ 1.  4.  7. 10.]


In [6]:
arr_ = np.linspace(1, 2, 10)       # create a 10 value between 1 to 2
print(arr_)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


#### reshape()
reshape is use to change the dimension of array

In [7]:
# first we create a 1d array
arr_1d = np.array([1, 2, 3 ,4 ,5 ,6 ,7 ,8, 9, 10, 11, 12])
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
# convert 1d to 2d by using reshape function
arr_2d = arr_1d.reshape(2, 6)        # reshape is use to change the dimension of array
print(arr_2d)                        # 2* 6 = 12   in 1d we have 12 items that's why we set according to 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
arr_2d = arr_1d.reshape(4, 3)         # 4*3 = 12
print(arr_2d)  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
# convert 1d to 3d array
arr_3d = arr_1d.reshape(3, 2, 2)         # 3*2*2 = 12   in 1d we have 12 items that' why
print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [11]:
arr_3d= arr_1d.reshape(2, 3, 2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### ravel ()
convert multi dimisional array to 1d <br>
NOTE: returns a view of the original array whenever possible

In [12]:
# 3d array (which we create above) to 1d array
arr_1d = arr_3d.ravel()
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
# 2s array (which we create above) to 1d array
arr_1d = arr_2d.ravel()
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### flatten
convert multi dimisional array to 1d <br>
Note: always returns a copy

In [14]:
arr_1d = arr_3d.flatten()
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### transpose
transpose is used to convert row into column

In [15]:
print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
arr_2d.transpose()  # or arr_2d.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [17]:
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
arr_3d.transpose()

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])