# NumPy Practical 05
Array Slicing

#### Import Library

In [1]:
import numpy as np

### Slicing

In [12]:
mx = np.arange(1, 101)            # create 1 to 100 item in array using arange function
mx = mx.reshape(10,10)            # convert 1d to 2d array using reshape function 

In [13]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [57]:
mx[:, 9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
# access first row and col element
mx[0, 0]

1

In [25]:
# acess first row and 6 column
mx[0, 5]

6

In [32]:
# acess 6 row and 7 colu
mx[6, 6]

67

In [33]:
# acess 5 , 6 column and 5 row
mx[5:7, 4]

array([55, 65])

In [17]:
# access first col and all row (1d)
mx[:, 0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [21]:
mx[:, 0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [22]:
# access first col and all row (2d)
mx[:, 0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [36]:
# acess 8, 9 col and row
mx[8: , 8:]

array([[ 89,  90],
       [ 99, 100]])

In [38]:
# acess 8, 9 row and 4, 5 column
mx[8: , 3:5 ]

array([[84, 85],
       [94, 95]])

In [47]:
# acess all row except last column
mx[0:, 0:9]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
# acess all row
mx[0:, 0:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [45]:
mx[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [46]:
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [50]:
# item size
mx.itemsize

4

In [51]:
# data type
mx.dtype       

dtype('int32')

In [52]:
32/8  # 4 bit is use to store mx 

4.0