# NumPy Practical 06
Concatenation and Split 

### Import Library

In [1]:
import numpy as np

### Concatenate Array

In [4]:
arr1 = np.arange(1,17).reshape(4, 4)
arr2 = np.arange(17, 33).reshape(4, 4)
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


#### Concatenate arrays by column (vertical)

In [6]:
np.concatenate((arr1, arr2), axis = 0)     #  axis = 0 (col)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [10]:
np.concatenate((arr1, arr2, arr1))         # by default axis = 0 and here we concatenate 3 array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

or

In [7]:
np.vstack((arr1, arr2))                 # vstack = vertical stack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [9]:
np.vstack((arr1, arr2, arr1, arr2))         # multiple array concatenate

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

#### Concatenate arrays by row (horizontal)

In [11]:
np.concatenate((arr1, arr2), axis = 1)                 # axis = 1 (row)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [12]:
np.concatenate((arr1, arr2, arr1), axis = 1)           # concatenate three arrays

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

or

In [13]:
np.hstack((arr1, arr2))            # hstack = horizontal stack

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [38]:
arr_3 = np.hstack((arr1, arr2, arr1, arr2))       # concatenate 4 arrays
arr_3

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16, 29, 30, 31, 32]])

### Split Array

In [39]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [40]:
print(arr_3)

[[ 1  2  3  4 17 18 19 20  1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24  5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28  9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32 13 14 15 16 29 30 31 32]]


#### Split by row

In [21]:
np.split(arr1, 2, axis = 0)          

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [ ]:
np.split

In [42]:
np.split(arr_3, 2)    # split into 2 

[array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4, 17, 18, 19, 20],
        [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8, 21, 22, 23, 24]]),
 array([[ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12, 25, 26, 27, 28],
        [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16, 29, 30, 31, 32]])]

In [43]:
np.split(arr_3, 4)   # split into 4

[array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4, 17, 18, 19, 20]]),
 array([[ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8, 21, 22, 23, 24]]),
 array([[ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12, 25, 26, 27, 28]]),
 array([[13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16, 29, 30, 31, 32]])]

#### Split by col

In [24]:
np.split(arr1, 2, axis =1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [68]:
np.split(arr_3, 2, axis = 1)

[array([[ 1,  2,  3,  4, 17, 18, 19, 20],
        [ 5,  6,  7,  8, 21, 22, 23, 24],
        [ 9, 10, 11, 12, 25, 26, 27, 28],
        [13, 14, 15, 16, 29, 30, 31, 32]]),
 array([[ 1,  2,  3,  4, 17, 18, 19, 20],
        [ 5,  6,  7,  8, 21, 22, 23, 24],
        [ 9, 10, 11, 12, 25, 26, 27, 28],
        [13, 14, 15, 16, 29, 30, 31, 32]])]

In [33]:
np.split(arr_3, 4, axis = 1)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]), array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [63]:
# Manual split
arr = np.array([1, 2, 4 ,5 ,7, 8, 9])
ms = np.split(arr, [1, 3, 5])
ms

[array([1]), array([2, 4]), array([5, 7]), array([8, 9])]

In [64]:
type(ms)          # its split into list

list