# NumPy Practical 08
Random Sampling

#### Import Library

In [2]:
import numpy as np
import  random

### Random Sampling

#### random.random()

In [2]:
# create a (1d) 3 random value between 0-1
np.random.random(3)

array([0.65539888, 0.58967567, 0.90419845])

In [3]:
# create a (1d) 6 random value between 0-1
np.random.random(6)

array([0.11315567, 0.95196795, 0.63528331, 0.98415121, 0.35683514,
       0.38825191])

In [4]:
# create a (2d) 2 col 2 row random value between 0-1
np.random.random((2, 2))

array([[0.19580785, 0.59939543],
       [0.38270473, 0.482387  ]])

In [7]:
# create a (2d) 2 col 2 row random value between 0-1
np.random.random((3, 4))

array([[0.67326659, 0.29050289, 0.59008357, 0.50920032],
       [0.12231544, 0.31137308, 0.38482536, 0.38242348],
       [0.38826994, 0.68038635, 0.61698576, 0.30598885]])

In [40]:
# create a (3d)  random value between 0-1
np.random.random((2, 3, 4))

array([[[0.87239246, 0.98302087, 0.46740328, 0.87574449],
        [0.2960687 , 0.13129105, 0.84281793, 0.6590363 ],
        [0.5954396 , 0.4363537 , 0.35625033, 0.58713093]],

       [[0.14947134, 0.1712386 , 0.39716452, 0.63795156],
        [0.37251995, 0.00240676, 0.54881636, 0.12697184],
        [0.07979268, 0.2350386 , 0.65996495, 0.21495319]]])

#### random.randint()

In [6]:
# create a random value between 2-4
np.random.randint(2, 4)

2

In [24]:
# create a random value between 5-10
np.random.randint(5,10)

7

In [23]:
# create a (2d) random value between 2-5
np.random.randint(2,5, (2, 2))                     # ( range, (row, col))

array([[3, 4],
       [2, 2]])

In [25]:
# create a (2d) random value between 1-5
np.random.randint(1,5, (4, 5))                     # ( range, (row, col))

array([[1, 2, 2, 4, 2],
       [2, 3, 3, 2, 2],
       [3, 1, 1, 3, 3],
       [1, 3, 2, 4, 2]])

In [39]:
# create a (23) random value between 1-5
np.random.randint(1,5, (4, 5, 4))                     # ( range, (3d))

array([[[3, 1, 2, 1],
        [3, 1, 3, 1],
        [4, 1, 1, 4],
        [4, 3, 1, 4],
        [3, 3, 2, 1]],

       [[1, 3, 2, 4],
        [3, 2, 2, 2],
        [4, 2, 3, 2],
        [1, 3, 3, 3],
        [2, 1, 2, 4]],

       [[2, 1, 4, 3],
        [2, 2, 3, 4],
        [3, 1, 4, 1],
        [3, 1, 2, 4],
        [3, 1, 3, 4]],

       [[1, 4, 2, 3],
        [4, 4, 1, 2],
        [1, 3, 1, 1],
        [1, 2, 1, 4],
        [1, 1, 3, 1]]])

####  np.random.seed()

In [29]:
np.random.seed(10)
np.random.randint(1, 5, (4 ,4))

array([[2, 2, 1, 4],
       [1, 2, 4, 1],
       [2, 2, 1, 2],
       [2, 3, 1, 2]])

In [32]:
# same print as above by using seed 
np.random.seed(10)
np.random.randint(1, 5, (4 ,4))

array([[2, 2, 1, 4],
       [1, 2, 4, 1],
       [2, 2, 1, 2],
       [2, 3, 1, 2]])

In [41]:
np.random.seed(10)
np.random.randint(2, 5, (2, 2 , 2))

array([[[3, 3],
        [2, 2]],

       [[3, 2],
        [3, 3]]])

In [42]:
# same print as above by using seed 
np.random.seed(10)
np.random.randint(2, 5, (2, 2 , 2))

array([[[3, 3],
        [2, 2]],

       [[3, 2],
        [3, 3]]])

#### np.random.rand()

In [38]:
# create(1d) 4 random values range between 0 ,1
np.random.rand(4)

array([0.44301495, 0.83191136, 0.58332174, 0.02517173])

In [68]:
# create 2d range between 0 ,1
np.random.rand(2, 3)             # (row, col)

array([[0.83487913, 0.21221285, 0.9619666 ],
       [0.26114034, 0.8637702 , 0.12687442]])

In [69]:
# create 3d range between 0 ,1
np.random.rand(2, 3, 3) 

array([[[0.37090221, 0.67193303, 0.93385224],
        [0.55889953, 0.67244911, 0.07705526],
        [0.24988623, 0.35558139, 0.02343209]],

       [[0.93512902, 0.20959771, 0.57677298],
        [0.58104733, 0.23392116, 0.48297919],
        [0.54704332, 0.87181231, 0.96403603]]])

#### np.random.randn()

In [70]:
# same as above but difference create a -ve and +ve values
np.random.randn(2)

array([0.23610191, 0.1617761 ])

In [71]:
# 1d
np.random.randn(2)

array([ 0.22555155, -1.1219324 ])

In [72]:
# 2d
np.random.randn(2, 3)

array([[ 1.20248351,  1.51133379, -1.87214559],
       [-0.64912164,  1.39491644,  1.04979671]])

In [73]:
# 3d
np.random.randn(4, 4 ,4)

array([[[-0.38924947, -0.64617433,  0.50132244,  0.55191692],
        [ 1.46127126, -0.14540648,  0.73097974, -0.61770627],
        [ 1.68435892, -0.87947247, -0.55992567, -0.17329043],
        [ 0.33455353,  2.14682753, -1.02172033, -0.80415941]],

       [[-2.04453685,  1.02078534, -0.09294796, -0.49084582],
        [-1.0889499 ,  1.08746733, -0.93793301, -0.84867503],
        [-1.27124735, -1.30212366, -0.80406783, -1.6515778 ],
        [ 0.28964567, -0.60966094, -0.29495329, -0.34159808]],

       [[ 1.22545095,  1.00308374, -2.33897791,  1.25085353],
        [ 1.97019742, -1.42818822, -1.00084459, -0.47007672],
        [-0.10003358,  1.06401267, -2.32304281,  0.59727058],
        [ 0.34824836, -0.14823938, -1.19640778,  0.14137642]],

       [[-0.48421859, -1.31026558, -0.58947099, -0.7802598 ],
        [-0.80252792, -1.22772372,  1.31766349,  1.16669796],
        [-0.41931019, -0.30383972,  0.52863211, -0.76114164],
        [-0.61322057, -1.28747267, -2.15194335,  0.66717803]]])

#### np.random.choice()
It choose random item between given array

In [74]:
x= [1, 4 ,3 ,7 , 9]
np.random.choice(x)

9

In [75]:
x= [1, 4 ,3 ,7 , 9]
np.random.choice(x)

7

In [76]:
x= [1, 4 ,3 ,7 , 9]
np.random.choice(x)

9

In [77]:
x= [1, 4 ,3 ,7 , 9]
np.random.choice(x)

7

In [78]:
x= [1, 4 ,3 ,7 , 9]
np.random.choice(x)

4

In [79]:
x= [1, 4 ,3 ,7 , 9]
np.random.choice(x)

9

In [80]:
x= [1, 4 ,3 ,7 , 9]
np.random.choice(x)

3

#### np.random.permutation()
It refers to the act or process of changing the linear order of an ordered set.

In [62]:
x = [3 ,1 ,4 ,2 ,7 , 8]
np.random.permutation(x)

array([2, 8, 1, 7, 3, 4])

In [63]:
x = [3 ,1 ,4 ,2 ,7 , 8]
np.random.permutation(x)

array([3, 7, 1, 8, 4, 2])

In [64]:
x = [3 ,1 ,4 ,2 ,7 , 8]
np.random.permutation(x)

array([2, 8, 4, 1, 7, 3])

In [65]:
x = [3 ,1 ,4 ,2 ,7 , 8]
np.random.permutation(x)

array([3, 2, 1, 4, 8, 7])